### ISSUE TITLE
C# code

### ISSUE THREAD

**Issue by dshookowsky** [martinzw/THRII-direct-USB-pedalboard#3]
Do you have any of your original C# code left? I have a THR10ii and I'd like to start with C# and make sure I have the communication working (even if it's inefficient) before converting to a raspberry pi pico or ESP32.

**Comment by martinzw** [comment]
Hi "dshookowsky",

I have invited you to my experimental C# Editor for THRII.
Please do not fork this in any way to the public . I want it to stay a private project!

But of course you can try it and study the code.

Martin

**Comment by dshookowsky** [comment]
Woops - first thing I did was fork it - I'll remove that fork - apologies
